name: 'Tofu Apply'
description: 'A GitHub Action to run tofu apply with all supported options.'
author: 'dnogu'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  working-directory:
    description: 'The directory in which to run tofu apply.'
    required: false
    default: '.'
  chdir:
    description: 'Switch working directory before executing tofu apply (--chdir).'
    required: false
    default: ''
  plan-file:
    description: 'Path to a saved plan file to apply. If provided, skips planning phase.'
    required: false
    default: ''
  auto-approve:
    description: 'Skip interactive approval of plan before applying (--auto-approve).'
    required: false
    default: 'false'
  destroy:
    description: 'Create a destroy plan (--destroy). Only available when not using a saved plan file.'
    required: false
    default: 'false'
  refresh-only:
    description: 'Create a refresh-only plan (--refresh-only). Only available when not using a saved plan file.'
    required: false
    default: 'false'
  refresh:
    description: 'Skip the default behavior of syncing state before applying (--refresh=false). Only available when not using a saved plan file.'
    required: false
    default: 'true'
  replace:
    description: 'Force replacement of particular resource instances (--replace=ADDRESS, comma separated). Only available when not using a saved plan file.'
    required: false
    default: ''
  target:
    description: 'Limit applying to only the given resource instances (--target=ADDRESS, comma separated). Only available when not using a saved plan file.'
    required: false
    default: ''
  target-file:
    description: 'Limit applying to resource instances listed in file (--target-file=FILE). Only available when not using a saved plan file.'
    required: false
    default: ''
  exclude:
    description: 'Exclude specific resource instances from applying (--exclude=ADDRESS, comma separated). Only available when not using a saved plan file.'
    required: false
    default: ''
  exclude-file:
    description: 'Exclude resource instances listed in file (--exclude-file=FILE). Only available when not using a saved plan file.'
    required: false
    default: ''
  var:
    description: 'Set input variable(s) (--var NAME=VALUE, comma separated). Only available when not using a saved plan file.'
    required: false
    default: ''
  var-file:
    description: 'Set input variables from file(s) (--var-file=FILENAME, comma separated). Only available when not using a saved plan file.'
    required: false
    default: ''
  compact-warnings:
    description: 'Show warning messages in compact form (--compact-warnings).'
    required: false
    default: 'false'
  consolidate-warnings:
    description: 'Consolidate similar warning messages (--consolidate-warnings).'
    required: false
    default: 'false'
  consolidate-errors:
    description: 'Consolidate similar error messages (--consolidate-errors).'
    required: false
    default: 'false'
  input:
    description: 'Ask for input if necessary (--input=true|false).'
    required: false
    default: 'false'
  json:
    description: 'Produce output in JSON format (--json). Requires --auto-approve or saved plan file.'
    required: false
    default: 'false'
  lock:
    description: 'Enable or disable state locking (--lock=true|false).'
    required: false
    default: 'true'
  lock-timeout:
    description: 'Override the time to wait for a state lock (--lock-timeout=DURATION).'
    required: false
    default: '0s'
  no-color:
    description: 'Disable color codes in output (--no-color).'
    required: false
    default: 'false'
  concise:
    description: 'Disable progress-related messages (--concise).'
    required: false
    default: 'false'
  parallelism:
    description: 'Limit the number of concurrent operations (--parallelism=n).'
    required: false
    default: '10'
  state:
    description: 'Legacy option for local backend only (--state=STATEFILE).'
    required: false
    default: ''
  state-out:
    description: 'Legacy option for local backend only (--state-out=STATEFILE).'
    required: false
    default: ''
  backup:
    description: 'Legacy option for local backend only (--backup=BACKUPFILE).'
    required: false
    default: ''
  show-sensitive:
    description: 'Display sensitive values in output (--show-sensitive).'
    required: false
    default: 'false'
  deprecation:
    description: 'Specify what type of warnings are shown (--deprecation=module:all|module:local|module:none).'
    required: false
    default: 'module:all'
  display-output:
    description: 'Display the apply output in the GitHub Actions log (true/false).'
    required: false
    default: 'true'
outputs:
  apply-output:
    description: 'The output from tofu apply.'
  exitcode:
    description: 'The exit code from tofu apply.'
branding:
  icon: 'check-circle'
  color: 'green'
